# Generated by Django 4.1.7 on 2023-03-26 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompositionAudd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "artist",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Жанр"
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Стиль"
                    ),
                ),
                (
                    "lyrics",
                    models.TextField(blank=True, null=True, verbose_name="Текст песни"),
                ),
                (
                    "release_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата релиза"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CompositionDiscogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "artist",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Жанр"
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Стиль"
                    ),
                ),
                (
                    "lyrics",
                    models.TextField(blank=True, null=True, verbose_name="Текст песни"),
                ),
                (
                    "release_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата релиза"),
                ),
                ("release", models.IntegerField(verbose_name="Release ID")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CompositionGenius",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "artist",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Жанр"
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Стиль"
                    ),
                ),
                (
                    "lyrics",
                    models.TextField(blank=True, null=True, verbose_name="Текст песни"),
                ),
                (
                    "release_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата релиза"),
                ),
                ("release", models.IntegerField(verbose_name="Release ID")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SearchName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "file",
                    models.FileField(
                        upload_to="", verbose_name="Файл для поиска в audd.io"
                    ),
                ),
                (
                    "audd",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="demo.compositionaudd",
                    ),
                ),
                (
                    "discogs",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="demo.compositiondiscogs",
                    ),
                ),
                (
                    "genius",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="demo.compositiongenius",
                    ),
                ),
            ],
        ),
    ]
